config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :links, only: [:show, :new, :create] do
    resource :upvotes, only: [:create]
    # resource :downvote, only: [:create]
  end
  root to: "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true

  def upvote
    increment!(:upvotes)
  end

  def score
    upvotes - downvotes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(link_params)
    
    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  private
  
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def create
    link = Link.find(params[:link_id])

    link.upvote
    
    redirect_back fallback_location: links_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@link.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTesting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_link.html.erb
<%= content_tag_for(:li, link) do %>
   <%= link_to link.title, link.url %>
  <%= link_to "Upvote", link_upvotes_path(link), method: :post %>
  <p data-role="score" > <%= link.upvotes.to_s %> </p>

<% end %> 

app/views/links/index.html.erb
<%= render partial: "link", collection: @links, as: :link || "no links" %>

<%= link_to "Submit a new link", new_link_path %>

app/views/links/new.html.erb
<%= form_for @link do |form| %>
  <%= render "error_messages", :target => @link %>


  <div>
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>
  
  <div>
  <%= form.label :url %>
  <%= form.text_field :url %>
  </div>
  
  <%= form.submit "Submit!" %>
  <% end %>

app/views/links/show.html.erb
<%= render partial: "link", locals: {link: @link} %>